version: '3'
services:
    mysql:
        container_name: lablab-mysql
        image: mysql:5.6
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: lablab-api
        ports:
            - 3306:3306
        volumes:
            - ./docker/mysql/data:/var/lib/mysql:rw
    php:
        container_name: lablab-php
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
            - .:/var/www/app:cached
        depends_on:
            - mysql
    nginx:
        container_name: lablab-nginx
        image: nginx:1.17-alpine
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/log/:/var/log/nginx/
            - ./public:/var/www/app/public
        ports:
            - 80:80
        depends_on:
            - php
